apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    pod: hello-world
  ports:
  - name: hello-world
    protocol: TCP
    port: 80
    targetPort: 8080
  externalIPs:
    - 192.168.1.11
